apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
data:
  REDIS_HOST: "{{ .Values.config.redis.host }}"
  REDIS_PORT: "{{ .Values.config.redis.port }}"
  REDIS_TIMEOUT: "{{ .Values.config.redis.timeout }}"
  RATE_LIMIT_ENABLED: "{{ .Values.config.rateLimit.enabled }}"
  RATE_LIMIT_GLOBAL_LIMIT: "{{ .Values.config.rateLimit.globalLimit }}"
  RATE_LIMIT_GLOBAL_WINDOW_SECONDS: "{{ .Values.config.rateLimit.windowSeconds }}"
