apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Worktree-Systems/platform-environments.git
    targetRevision: HEAD
    path: helm-charts/api-gateway
    helm:
      valueFiles:
        - ../../dev/api-gateway/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
