replicaCount: 2

image:
  repository: 971997843851.dkr.ecr.ap-south-1.amazonaws.com/api-gateway
  tag: 41
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 2020

resources:
  limits:
    cpu: "1000m"
    memory: "1Gi"
  requests:
    cpu: "300m"
    memory: "512Mi"

env:
  SPRING_PROFILES_ACTIVE: k8s

config:
  redis:
    host: redis-master
    port: "6379"
    timeout: "2000"
  rateLimit:
    enabled: "true"
    globalLimit: "1000"
    windowSeconds: "60"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  host: api.dev.worktree-hrms.shop
  certificateArn: arn:aws:acm:ap-south-1:xxxx:certificate/xxxx

serviceAccount:
  name: api-gateway-sa
  roleArn: ""
